{
 "title": "Expense",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{exported_name=\"nginx.service\", state=\"active\"}",
     "legendFormat": "{{exported_name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"backend.service\", state=\"active\"}",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)/node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Queued / Dropped ",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(node_ethtool_pps_allowance_exceeded[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ec2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}